spring:
  application:
    name: app

  security:
    user:
      name: admin
      password: admin

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: JavaMTS

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgresSQLDialect
      ddl-auto: validate
    flyway:
      enabled: true
      locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:29093}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topic:
  audit: audit-topic

# Настройка scheduler-а для outbox
outbox:
  scheduler:
    # период опроса и отправки записей (в миллисекундах)
    delay: 5000

springdoc:
  swagger-ui:
    path: /api-docs
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
      base-path: /admin/actuator
  endpoint:
    health:
      show-details: always
    metrics:
      distribution:
        percentiles-histogram: true

server:
  port: 8080
  tomcat:
    threads:
      max: 210
      min-spare: 10

resilience4j:
  ratelimiter:
    instances:
      apiRateLimiter:
        limit-for-period: 5
        limit-refresh-period: 10s
        timeout-duration: 0
  circuitbreaker:
    instances:
      apiCircuitBreaker:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
        sliding-window-size: 10

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.app: DEBUG
