global:
  scrape_interval: 15s

scrape_configs:
  # Сам Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot + Micrometer
  - job_name: 'spring-actuator'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8080']